/*
 * Automatically generated by png2c
 *
 * $Id: printer_image.h,v 1.1 2013/01/31 22:42:22 rzookol Exp $
 */


extern unsigned long Printer[];
#define PRINTER_WIDTH 120
#define PRINTER_HEIGHT 110
#define PRINTER_DEPTH 32
